### ISSUE TITLE
mergeGeometries vs mergeBufferGeometries with Three 0.161.0

### ISSUE THREAD

**Issue by teddybee** [pmndrs/react-three-gpu-pathtracer#10]
When i want to use the path tracer component I always got this error:
```
import * as BufferGeometryUtils from 'three/addons/utils/BufferGeometryUtils.js';
```
```
./node_modules/three-gpu-pathtracer/src/utils/GeometryPreparationUtils.js
Attempted import error: 'mergeBufferGeometries' is not exported from 'three/examples/jsm/utils/BufferGeometryUtils.js' (imported as 'mergeBufferGeometries').
```

I figured out that three/addons/utils/BufferGeometryUtils.js has no mergeBufferGeometries export just a mergeGeometries.

I used R3F 8.15.16 and Nextjs 14.1,0

Are those two exports identical? How can I eliminate the error?

**Comment by FarazzShaikh** [comment]
Seems like an upsteeam issue. Please follow up with three-gpu-pathtracer
