### ISSUE TITLE
THREE.BufferGeometryUtils: .mergeGeometries() failed while trying to merge the color attribute.   

### ISSUE THREAD

**Issue by goldenjayr** [pmndrs/react-three-gpu-pathtracer#6]
tried to use this on my vite react app but it says
THREE.BufferGeometryUtils: .mergeGeometries() failed while trying to merge the color attribute. 

All the react, three, fiber drei versions are latest

not sure why it is doing that.
 
<img width="894" alt="Screenshot 2023-05-03 at 6 54 35 PM" src="https://user-images.githubusercontent.com/37247707/235896980-3848c565-df99-47f4-ae5d-0fa33e8f94da.png">

**Comment by teddybee** [comment]
Same here, with nextjs 14
