### ISSUE TITLE
While Loading GLB, the geometry gets weird

### ISSUE THREAD

**Issue by aditya03av** [pmndrs/react-three-gpu-pathtracer#8]
While loading the GLB, the geometry mesh becomes wierd. Do you know, why? 
<img width="957" alt="Screenshot 2023-09-27 at 8 04 33 PM" src="https://github.com/pmndrs/react-three-gpu-pathtracer/assets/128450417/32279f40-cf36-421c-b7f2-14f1bb66b3d4">

**Comment by lklyne** [comment]
Having the same issue. Updated drei to latest version `9.88.17` so environment maps will load and also getting weird geometry with the starting scene. Not sure if @FarazzShaikh has a fix or is still maintaining this library?
![image](https://github.com/pmndrs/react-three-gpu-pathtracer/assets/6529667/b168c907-5c96-41af-b92c-dbafdbf78cd8)

**Comment by lklyne** [comment]
Guessing we are both using M1 apple devices? I see there's an open issue on three-gpu-pathtracer with a similar issue — could be an apple bug. https://github.com/gkjohnson/three-gpu-pathtracer/issues/464

**Comment by FarazzShaikh** [comment]
Upstream issue seems to be fixed. Please try it again and re-open if it persists.
