### ISSUE TITLE
Not working in Chrome Version 119.0.6045.159 on M1 chip

### ISSUE THREAD

**Issue by akshaaatt** [pmndrs/react-three-gpu-pathtracer#9]
![Screenshot 2023-11-22 at 12 42 18 PM](https://github.com/pmndrs/react-three-gpu-pathtracer/assets/51470769/54517796-a5db-45a7-b7eb-148048326c7e)

**Comment by lklyne** [comment]
I too am using an M1 and chrome version `119.0.6045.159` and things are working. I did update the three-gpu-pathtracer dependency to the latest version, but things were working fine before that as well. Any other potential causes?
